[tools]
bun = "latest"
cargo-binstall = "latest"
deno = "latest"
fnox = "latest"
node = "lts"
pipx = "latest"
pixi = "latest"
poetry = "latest"
python = "3.14"
rust = "latest"
usage = "latest"
uv = "latest"
yarn = "1.22.22"
